name: Automatically deploy to nest
on: [push]

jobs:
  deploy-to-nest:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to ssh, pull and systemctl restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            : # Load nix binaries
            export PATH=/home/skyfall/.nix-profile/bin:$PATH
            export PATH=/nix/skyfall/nix/profiles/default/bin:$PATH
            cd /home/skyfall/shiptalkers
            git pull
            bun install
            systemctl --user restart shiptalkers.service
            echo "Done!"
